name: Clients CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build_android_debug:
    if: false
    runs-on: ubuntu-latest
    steps:
      - name: Checkout GIT
        uses: actions/checkout@v4

      - name: Setup Java SDK
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: '18'

      - name: Gradle cache
        uses: gradle/actions/setup-gradle@v4

      - name: Build Debug APK
        run: ./gradlew :composeApp:assembleDebug

      - name: Upload APK to Github Actions
        uses: actions/upload-artifact@v4
        with:
          name: Ivy-Learn-Debug.apk
          path: composeApp/build/outputs/apk/debug/composeApp-debug.apk

  build_web_prod:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout GIT
        uses: actions/checkout@v4

      - name: Setup Java SDK
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: '18'

      - name: Gradle cache
        uses: gradle/actions/setup-gradle@v4

      - name: Build Web distribution
        run: ./gradlew :composeApp:jsBrowserDistribution

  unit_test_clients:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout GIT
        uses: actions/checkout@v4

      - name: Setup Java SDK
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: '18'

      - name: Gradle cache
        uses: gradle/actions/setup-gradle@v4

      - name: Run unit tests on JS
        run: ./gradlew jsTest

